etl_pipeline:
  load_local: True
  rewrite_log: True
  run_extraction: True
  run_transformation: True
  run_loading: True

file_types:
  valid_file_extensions:
    xls: "application/vnd.ms-excel"
    xlsx: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"

column_match_threshold: 90
row_density_threshold: 0.7
row_string_density_threshold: 0.5

dtype_map:
  {
    "string": "string",
    "float": "float64",
    "float64": "float64",
    "int64": "int64",
    "object": "object",
    "int": "int64",
    "boolean": "bool",
    "date": "datetime64[ns]",
    "datetime64[ns]": "datetime64[ns]",
  }

template_data:
  warehause_address:
    {
      "100": "Im Weinhof 36 Hagen DE 58119",
      "139": "Oeger Straße 11-35 Hagen DE 58119",
      "127": "Unterberchum 30 Hagen DE 58093",
      "101": "Im Weinhof 36 Hagen DE 58119",
    }
  action_type: "Blind"
  access: "Open"
  choice: "2nd"

google_folder_id: "1ZmDDaCkE2ZyWOYvksTeveim2-vWoR1b8"
