etl_pipeline:
  load_local: True
  rewrite_log: True
  run_extraction: True
  run_transformation: True
  run_loading: True

file_types:
  valid_file_extensions:
    xls: "application/vnd.ms-excel"
    xlsx: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"

column_match_threshold: 90
row_density_threshold: 0.7
row_string_density_threshold: 0.5

dtype_map:
  {
    "string": "string",
    "float": "float64",
    "float64": "float64",
    "int64": "int64",
    "object": "object",
    "int": "int64",
    "boolean": "bool",
    "date": "datetime64[ns]",
    "datetime64[ns]": "datetime64[ns]",
  }

template_data:
  warehause_address:
    {
      "100":
        {
          "address": "Im Weinhof 36 Hagen DE 58119",
          "UUID": "b2c744a8-11ef-4f67-9788-1a28054b7a50",
        },
      "139":
        {
          "address": "Oeger Straße 11-35 Hagen DE 58119",
          "UUID": "09760b77-355d-44c9-ada0-0be2b841be3f",
        },
      "127":
        {
          "address": "Unterberchum 30 Hagen DE 58093",
          "UUID": "73091e0e-647a-4081-833f-b3f59451e4a4",
        },
      "101":
        {
          "address": "Im Weinhof 36 Hagen DE 58119",
          "UUID": "b2c744a8-11ef-4f67-9788-1a28054b7a50",
        },
      "200":
        {
          "address": "Alemannenweg 29 Hagen DE 58119",
          "UUID": "11f234c3-f0f5-487a-b131-3629c5c9d665",
        },
      "300":
        {
          "address": "Im Weinhof 36 Hagen DE 58119",
          "UUID": "b2c744a8-11ef-4f67-9788-1a28054b7a50",
        },
    }
  action_type: "Blind"
  access: "Open"
  choice: "2nd"
  auction_tag: "repeated"

google_folder_id: "1ZmDDaCkE2ZyWOYvksTeveim2-vWoR1b8"
